create table roles (
    id   bigint generated by default as identity primary key,
    name varchar(20) not null unique
);

create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    password_hash varchar(100) not null,
    first_name    varchar(100) not null,
    last_name     varchar(100) not null,
    phone         varchar(32),
    status        varchar(20)  not null,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null
);

create table user_roles (
    user_id bigint not null references users (id) on delete cascade,
    role_id bigint not null references roles (id),
    primary key (user_id, role_id)
);

create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    token_hash varchar(64) not null unique,
    user_agent varchar(255),
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null
);

create index idx_refresh_tokens_user on refresh_tokens (user_id);

insert into roles (name) values ('CLIENT'), ('EMPLOYEE'), ('ADMIN');
