create table clients (
    id                bigint generated by default as identity primary key,
    user_id           bigint      not null unique references users (id) on delete cascade,
    loyalty_tier      varchar(20),
    marketing_consent boolean     not null default false,
    created_at        timestamptz not null,
    updated_at        timestamptz not null
);
