create table service_categories (
    id            bigint generated by default as identity primary key,
    name          varchar(100) not null unique,
    description   varchar(500),
    display_order integer      not null default 0,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null
);

create table services (
    id                     bigint generated by default as identity primary key,
    category_id            bigint         not null references service_categories (id),
    code                   varchar(40)    not null unique,
    name                   varchar(150)   not null,
    description            varchar(1000),
    base_price             numeric(10, 2) not null,
    duration_minutes       integer        not null,
    buffer_minutes         integer        not null default 0,
    resource_type_required varchar(20),
    active                 boolean        not null default true,
    created_at             timestamptz    not null,
    updated_at             timestamptz    not null,
    constraint services_base_price_non_negative check (base_price >= 0),
    constraint services_duration_positive check (duration_minutes > 0),
    constraint services_buffer_non_negative check (buffer_minutes >= 0)
);

create index idx_services_category on services (category_id);
create index idx_services_active on services (active);
