create table resources (
    id            bigint generated by default as identity primary key,
    name          varchar(100) not null unique,
    resource_type varchar(20)  not null,
    active        boolean      not null default true,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null
);
