create table employees (
    id                bigint generated by default as identity primary key,
    user_id           bigint       not null unique references users (id) on delete cascade,
    display_name      varchar(150) not null,
    title             varchar(100),
    employment_status varchar(20)  not null,
    hired_on          date         not null,
    created_at        timestamptz  not null,
    updated_at        timestamptz  not null
);

create table employee_working_hours (
    id          bigint generated by default as identity primary key,
    employee_id bigint     not null references employees (id) on delete cascade,
    day_of_week varchar(9) not null,
    start_time  time       not null,
    end_time    time       not null,
    constraint uq_working_hours_employee_day unique (employee_id, day_of_week),
    constraint working_hours_time_order check (start_time < end_time)
);

create index idx_working_hours_employee on employee_working_hours (employee_id);

create table employee_time_off (
    id          bigint generated by default as identity primary key,
    employee_id bigint      not null references employees (id) on delete cascade,
    starts_at   timestamptz not null,
    ends_at     timestamptz not null,
    reason      varchar(255),
    created_at  timestamptz not null,
    updated_at  timestamptz not null,
    constraint time_off_time_order check (starts_at < ends_at)
);

create index idx_time_off_employee on employee_time_off (employee_id);

create table employee_skills (
    id          bigint generated by default as identity primary key,
    employee_id bigint not null references employees (id) on delete cascade,
    service_id  bigint not null references services (id),
    constraint uq_employee_skill unique (employee_id, service_id)
);

create index idx_employee_skills_service on employee_skills (service_id);
