create extension if not exists btree_gist;

create table appointments (
    id                      bigint generated by default as identity primary key,
    client_id               bigint         not null references clients (id),
    employee_id             bigint         not null references employees (id),
    resource_id             bigint         references resources (id),
    status                  varchar(20)    not null,
    scheduled_start         timestamptz    not null,
    scheduled_end           timestamptz    not null,
    net_amount              numeric(10, 2) not null,
    surcharge_amount        numeric(10, 2) not null,
    discount_percentage     numeric(5, 2)  not null,
    discount_amount         numeric(10, 2) not null,
    total_amount            numeric(10, 2) not null,
    loyalty_tier_at_booking varchar(20),
    cancellation_reason     varchar(255),
    cancelled_at            timestamptz,
    cancelled_by_user_id    bigint,
    version                 bigint         not null,
    created_at              timestamptz    not null,
    updated_at              timestamptz    not null,
    constraint appointments_time_order check (scheduled_start < scheduled_end)
);

create index idx_appointments_client on appointments (client_id);
create index idx_appointments_employee_start on appointments (employee_id, scheduled_start);

alter table appointments
    add constraint appointments_no_employee_overlap
        exclude using gist (
            employee_id with =,
            tstzrange(scheduled_start, scheduled_end) with &&
        ) where (status <> 'CANCELLED' and status <> 'NO_SHOW');

alter table appointments
    add constraint appointments_no_resource_overlap
        exclude using gist (
            resource_id with =,
            tstzrange(scheduled_start, scheduled_end) with &&
        ) where (resource_id is not null and status <> 'CANCELLED' and status <> 'NO_SHOW');

create table appointment_items (
    id             bigint generated by default as identity primary key,
    appointment_id bigint         not null references appointments (id) on delete cascade,
    service_id     bigint         not null references services (id),
    quantity       smallint       not null,
    unit_price     numeric(10, 2) not null,
    line_amount    numeric(10, 2) not null,
    constraint appointment_items_quantity_positive check (quantity > 0)
);

create index idx_appointment_items_appointment on appointment_items (appointment_id);
