create table loyalty_tiers (
    id                         bigint generated by default as identity primary key,
    name                       varchar(30)    not null unique,
    min_completed_appointments integer        not null,
    min_lifetime_spend         numeric(12, 2) not null,
    discount_percentage        numeric(5, 2)  not null,
    display_order              integer        not null,
    created_at                 timestamptz    not null,
    updated_at                 timestamptz    not null
);

create table pricing_rules (
    id                    bigint generated by default as identity primary key,
    code                  varchar(40)   not null unique,
    description           varchar(255),
    adjustment_percentage numeric(5, 2) not null,
    days_of_week          varchar(20),
    time_from             time,
    time_to               time,
    priority              integer       not null,
    active                boolean       not null default true,
    created_at            timestamptz   not null,
    updated_at            timestamptz   not null
);

insert into loyalty_tiers
    (name, min_completed_appointments, min_lifetime_spend, discount_percentage, display_order, created_at, updated_at)
values
    ('BRONZE', 0, 0.00, 0.00, 1, now(), now()),
    ('SILVER', 3, 500.00, 5.00, 2, now(), now()),
    ('GOLD', 10, 2000.00, 10.00, 3, now(), now());

insert into pricing_rules
    (code, description, adjustment_percentage, days_of_week, time_from, time_to, priority, active, created_at, updated_at)
values
    ('WEEKEND_SURCHARGE', 'Saturday and Sunday premium', 15.00, '6,7', null, null, 10, true, now(), now()),
    ('AFTER_HOURS_SURCHARGE', 'Evening premium from 18:00', 10.00, null, '18:00', '23:59:59', 20, true, now(), now());
