create sequence invoice_number_seq start with 1 increment by 1;

create table invoices (
    id             bigint generated by default as identity primary key,
    appointment_id bigint         not null unique references appointments (id),
    invoice_number varchar(30)    not null unique,
    status         varchar(20)    not null,
    issued_at      timestamptz    not null,
    due_date       date           not null,
    net_amount     numeric(10, 2) not null,
    tax_rate       numeric(4, 3)  not null,
    tax_amount     numeric(10, 2) not null,
    gross_amount   numeric(10, 2) not null,
    version        bigint         not null,
    created_at     timestamptz    not null,
    updated_at     timestamptz    not null
);

create table payments (
    id                  bigint generated by default as identity primary key,
    invoice_id          bigint         not null references invoices (id) on delete cascade,
    amount              numeric(10, 2) not null,
    method              varchar(20)    not null,
    paid_at             timestamptz    not null,
    reference           varchar(100),
    recorded_by_user_id bigint,
    constraint payments_amount_positive check (amount > 0)
);

create index idx_payments_invoice on payments (invoice_id);
